# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RS-service
  # tìm hiểu về cách dùng namespace
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
  selector:
    app: RS-app
  
